### ISSUE TITLE
Overrides "Description" button

### ISSUE THREAD

**Issue by seanniu93** [telotortium/anki-reset-limits#3]
Without addon:

![image](https://user-images.githubusercontent.com/9022274/137252569-fffe9983-dd4e-4bda-a962-5e81fe9d079c.png)

With addon:

![image](https://user-images.githubusercontent.com/9022274/137252591-50cf62fa-46c6-4ef5-adf8-dd80e146de24.png)

**Comment by telotortium** [comment]
Hi, which Anki version are you running?

**Comment by seanniu93** [comment]
2.1.48 on Windows. I think the button was added in 2.1.45: “The deck
description is now accessible via a button in the overview screen, instead
of via the deck options.”

**Comment by telotortium** [comment]
I've merged a fix and uploaded it to AnkiWeb.

**Comment by seanniu93** [comment]
Thanks! You’re awesome.
